### ISSUE TITLE
strange build fail in circleci

### ISSUE THREAD

**Issue by codefromthecrypt** [hypertrace/hypertrace-service#26]
There's a connection failure in circleci preventing the build from continuing

"com.bmuschko.gradle.docker.shaded.org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:2375 [/127.0.0.1] failed: Connection refused (Connection refused)"

https://app.circleci.com/pipelines/github/hypertrace/hypertrace-service/135/workflows/d8a5141f-41b4-4da9-85f0-26c2ba52522a/jobs/387

snippet
```
Using images 'hypertrace/hypertrace:main'.

Selected ExecutorServiceProvider implementation [com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.DefaultClientAsyncExecutorProvider] to be used for injection of executor qualified by [com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.ClientAsyncExecutor] annotation.

Selected ScheduledExecutorServiceProvider implementation [com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.DefaultClientBackgroundSchedulerProvider] to be used for injection of scheduler qualified by [com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.ClientBackgroundScheduler] annotation.



Error during callback

com.bmuschko.gradle.docker.shaded.org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:2375 [/127.0.0.1] failed: Connection refused (Connection refused)

	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)

	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)

	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)

	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)

	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)

	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)

	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)

	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)

	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)

	at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:480)

	at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:296)

	at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:623)

	at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:292)

	at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:274)

	at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:205)

	at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)

	at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:621)

	at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:432)

	at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:333)

	at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:30)

	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:51)

Caused by: java.net.ConnectException: Connection refused (Connection refused)

	at com.bmuschko.gradle.docker.shaded.org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)

	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)

	... 20 more



> Task :hypertrace-service:dockerBuildImage_default FAILED

:hypertrace-service:dockerBuildImage_default (Thread[Daemon worker,5,main]) completed. Took 2.346 secs.


```

**Comment by adriancole** [comment]
https://github.com/hypertrace/hypertrace-service/pull/28 passed, so checking to see if something odd about the last commit, or if there's a real error obfuscated by the localhost fail

**Comment by adriancole** [comment]
wild guess is we setup the repo #27 and see if it magically gets rid of this error. the fail is unrelated to tests https://app.circleci.com/pipelines/github/hypertrace/hypertrace-service/138/workflows/63fa44ee-85e6-4f57-8fcf-7bba6ad6d902/jobs/397

**Comment by kotharironak** [comment]
closing this as we moved to github actions.
