### ISSUE TITLE
Poor exception handling on no data

### ISSUE THREAD

**Issue by adriancole** [hypertrace/hypertrace-service#40]
When there's no data, it should be handled gracefully or some sort of error code. Thanks @kishoreg for noticing

```
^[[36mhypertrace              |^[[0m org.apache.pinot.client.PinotClientException: Could not find broker to query for table: null
^[[36mhypertrace              |^[[0m    at org.apache.pinot.client.Connection.execute(Connection.java:124) ~[pinot-java-client-0.5.0.jar:0.5.0-d87bbc9032c6efe626eb5f9ef1db4de7aa067179]
^[[36mhypertrace              |^[[0m    at org.apache.pinot.client.Connection.execute(Connection.java:96) ~[pinot-java-client-0.5.0.jar:0.5.0-d87bbc9032c6efe626eb5f9ef1db4de7aa067179]
^[[36mhypertrace              |^[[0m    at org.apache.pinot.client.PreparedStatement.execute(PreparedStatement.java:72) ~[pinot-java-client-0.5.0.jar:0.5.0-d87bbc9032c6efe626eb5f9ef1db4de7aa067179]
^[[36mhypertrace              |^[[0m    at org.hypertrace.core.query.service.pinot.PinotClientFactory$PinotClient.executeQuery(PinotClientFactory.java:84) ~[query-service-impl.jar:?]
^[[36mhypertrace              |^[[0m    at org.hypertrace.core.query.service.pinot.PinotBasedRequestHandler.lambda$handleRequest$4(PinotBasedRequestHandler.java:346) ~[query-service-impl.jar:?]
```

**Comment by kotharironak** [comment]
This PR - https://github.com/hypertrace/hypertrace-service/pull/39 - fixes this issue.

**Comment by kotharironak** [comment]
verified the fix - https://github.com/hypertrace/hypertrace-service/pull/39, don't see above exceptions on startup. Closing this.
